
services:

  scm_project:
    image: jaga9989/scm_project:app
    ports:
      - "8000:8000"

  kafka:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller # KRaft Mode
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 # Single Broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - scm_project

  server:
    image: jaga9989/scm_project:server
    depends_on:
      - kafka

  producer:
    image: jaga9989/scm_project:producer
    depends_on:
      - server
      - kafka
    environment:
      - host=server

  consumer:
    image: jaga9989/scm_project:consumer
    depends_on:
      - producer
      - server
      - kafka 